# DO NOT CHANGE THE FIRST 2 SETTINGS
firstRun: true
firstRunDone: false
modeSet: false
debugCommands: true
enable: true
storageType: FLATFILE
enableLobbyProtection: false
saving: true
serverStatus: MODEUNSET
autosetupRun: false
ignoreWorlds:
  - 'world_the_end'
  - 'world_nether'
dedicatedSSBWorlds:
  - 'world'
dedicatedSSB: false
inventorySave: false
useWorldManager: true
worldGenerator: false
generateDefaultWorld: false
worldGenerateStage: 1
worldGeneratorPlugin: 'CleanroomGenerator:.'
worldDefault: 'world'
newWorldDefault: 'SSB'
disableTheEnd: false
firstJoinOverride: true
classesEnabled:
  - Creeper
threads:
    timerScheduled: 2
    useLoginService: false
    loginThreads: 0
gemshop:
  ecoPlugin: false
  itemOpen:
    open: true
    item: "Material_Emerald"
    displayName: "Super Sky Bros Shop"
    lore:
      - "&4Sorry the shop is closed"
      - "&aStill in Development"
    slot: 8
joinBook:
  enable: true
  slot: 0
  displayName: '&aSuper Sky Bros Guide'
  lore:
    - '&5Get Help on Playing'
    - '&5Donor Ranks'
  pageOneTitle: '&8Super Sky Bros'
  author: '&aRelicum and Co'
  pages:
    - page:
      - number: 1
      - lines:
        - '&aWelcome to the SSB Guide'
        - '&5Here you will find a basic guide'
        - '&5to get you started.'
      - page:
        - number: 2
        - lines:
          - '&5This is displaing on page 2'
          - '&5The good can have 250 pages'
#Color Console Messages
#True is that console messages will have color
coloredConsole:
    colorConsole: true
#Set to false to disable info color
    infoColor: true
#Set to false to disable warning color
    warningColor: true
#set to false to disable serve color
    serveColor: true
rel:
  lines:
    line:
    - '&b<<     ----------------------------------------     >>'
    - '&2#                                                                 #'
    - '&2#                      &4SUPER&7&l-&bSKY&7&l-&6BROS&7&l-&aBRAWL                  &2#'
    - '&2#               &6Download it free for your server            &2#'
    - '&2#                                                                #'
    - '&2#&5      dev.bukkit.org/bukkit-plugins/superskybros/     &2#'
    - '&b<<     ----------------------------------------     >>'

